from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StereoWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 16pt \"Arial\";\n"
"color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 1920, 1022))
        self.background_label.setMinimumSize(QtCore.QSize(1920, 1022))
        self.background_label.setMaximumSize(QtCore.QSize(1920, 1022))
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("system_data/background_dark.png"))
        self.background_label.setScaledContents(True)
        self.background_label.setObjectName("background_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 1022))
        self.widget.setMinimumSize(QtCore.QSize(1920, 1022))
        self.widget.setMaximumSize(QtCore.QSize(1920, 1022))
        self.widget.setStyleSheet("background-color: rgba(255, 0, 0, 0);")
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_image = QtWidgets.QLabel(self.widget)
        self.label_image.setMinimumSize(QtCore.QSize(0, 1022))
        self.label_image.setMaximumSize(QtCore.QSize(16777215, 1022))
        self.label_image.setObjectName("label_image")
        self.gridLayout_5.addWidget(self.label_image, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(500, 1022))
        self.widget_2.setMaximumSize(QtCore.QSize(500, 1022))
        self.widget_2.setStyleSheet("background-color:rgb(40, 40, 40);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(400, 90))
        self.label_2.setMaximumSize(QtCore.QSize(400, 90))
        self.label_2.setStyleSheet("font: 40pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setMinimumSize(QtCore.QSize(204, 60))
        self.label_3.setMaximumSize(QtCore.QSize(204, 60))
        self.label_3.setStyleSheet("font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setMinimumSize(QtCore.QSize(204, 60))
        self.label_4.setMaximumSize(QtCore.QSize(204, 60))
        self.label_4.setStyleSheet("font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(64, 60))
        self.label_5.setMaximumSize(QtCore.QSize(64, 60))
        self.label_5.setStyleSheet("font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox.setMinimumSize(QtCore.QSize(184, 60))
        self.spinBox.setMaximumSize(QtCore.QSize(184, 60))
        self.spinBox.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 30pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_2.setMinimumSize(QtCore.QSize(184, 60))
        self.spinBox_2.setMaximumSize(QtCore.QSize(184, 60))
        self.spinBox_2.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 30pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setMinimumSize(QtCore.QSize(64, 60))
        self.label_6.setMaximumSize(QtCore.QSize(64, 60))
        self.label_6.setStyleSheet("font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_3.setMinimumSize(QtCore.QSize(184, 60))
        self.spinBox_3.setMaximumSize(QtCore.QSize(184, 60))
        self.spinBox_3.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 30pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_4.addWidget(self.spinBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.spinBox_4 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_4.setMinimumSize(QtCore.QSize(184, 60))
        self.spinBox_4.setMaximumSize(QtCore.QSize(184, 60))
        self.spinBox_4.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 30pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setMinimumSize(QtCore.QSize(64, 60))
        self.label_7.setMaximumSize(QtCore.QSize(64, 60))
        self.label_7.setStyleSheet("font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBox_5 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_5.setMinimumSize(QtCore.QSize(184, 60))
        self.spinBox_5.setMaximumSize(QtCore.QSize(184, 60))
        self.spinBox_5.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 30pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.spinBox_6 = QtWidgets.QSpinBox(self.widget_2)
        self.spinBox_6.setMinimumSize(QtCore.QSize(184, 60))
        self.spinBox_6.setMaximumSize(QtCore.QSize(184, 60))
        self.spinBox_6.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 30pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_5.addWidget(self.spinBox_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label.setStyleSheet("font: 28pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_1.setMinimumSize(QtCore.QSize(224, 60))
        self.pushButton_1.setMaximumSize(QtCore.QSize(224, 60))
        self.pushButton_1.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_11.addWidget(self.pushButton_1)
        spacerItem7 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(224, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(224, 60))
        self.pushButton_2.setStyleSheet("background-color:rgb(60, 60, 60);\n"
"font: 22pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 30))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.menu_2.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_8)
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_image.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", " Стерео пара"))
        self.label_3.setText(_translate("MainWindow", "OX:"))
        self.label_4.setText(_translate("MainWindow", "OY:"))
        self.label_5.setText(_translate("MainWindow", "R:"))
        self.label_6.setText(_translate("MainWindow", "G:"))
        self.label_7.setText(_translate("MainWindow", "B:"))
        self.label.setText(_translate("MainWindow", " Подтвердить?"))
        self.pushButton_1.setText(_translate("MainWindow", "Да"))
        self.pushButton_2.setText(_translate("MainWindow", "Нет"))
        self.menu_2.setTitle(_translate("MainWindow", "Информация об изображении"))
        self.action.setText(_translate("MainWindow", "Сохранить"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_2.setText(_translate("MainWindow", "Убрать"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_4.setText(_translate("MainWindow", "Загрузить"))
        self.action_4.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.action_5.setText(_translate("MainWindow", "Имя:"))
        self.action_6.setText(_translate("MainWindow", "Формат:"))
        self.action_7.setText(_translate("MainWindow", "Размеры:"))
        self.action_8.setText(_translate("MainWindow", "Цветовая модель:"))
